# Generated by Django 5.1.3 on 2024-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(choices=[('T-shirt', 'T-shirt'), ('Blazers', 'Blazers'), ('Sunglass', 'Sunglass'), ('Kids', 'Kids'), ('Polo shirt', 'Polo shirt')], max_length=20)),
            ],
        ),
    ]
