# Generated by Django 5.1.3 on 2024-12-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='category',
        ),
        migrations.AlterField(
            model_name='product_list',
            name='image',
            field=models.ImageField(upload_to='ecommerce/index/image/'),
        ),
    ]
