# Generated by Django 5.1.3 on 2024-12-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_product_list_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_list',
        ),
    ]
